version: "3"
services:
    app-nginx:
        build:
            context: manager/docker
            dockerfile: nginx.dockerfile
        volumes:
            - ./manager:/app
        depends_on:
            - app-php-fpm
        ports:
            - 8080:80
    app-php-fpm:
        build:
            context: manager/docker
            dockerfile: php-fpm.dockerfile
        volumes:
            - ./manager:/app
    app-php-cli:
        build:
            context: manager/docker
            dockerfile: php-cli.dockerfile
        volumes:
            - ./manager:/app
    app-mysql:
        image: mysql:5.7
        volumes:
            - mysql:/var/lib/mysql
        environment:
            - "MYSQL_USER=app"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=app"
            - "MYSQL_ROOT_PASSWORD=secret"
        ports:
            - 33066:3306
    app-mailer:
        image: mailhog/mailhog
        ports:
            - "8020:8025"
    app-node:
        image: node:14.6-alpine
        volumes:
            - ./manager:/app
        working_dir: /app
volumes:
    mysql: